name: Task
description: タスク作成のテンプレート
body:
  - type: markdown
    attributes:
      value: |
        詳細な情報は[こちら](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)を参照してください。
  - type: textarea
    id: gaiyo
    attributes:
      label: 概要
      description: |
        概要を書く。
        概要を書いてください。
  - type: textarea
    id: design
    attributes:
      label: 設計
      description: |
        設計を書く
        - ああ
        - いいい
  - type: textarea
    id: ready-check
    attributes:
      label: Ready の条件
      value: |
        - [ ] 条件1
        - [ ] 条件2
        - [ ] 条件3
