name: Task
description: タスク作成のテンプレート
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to create a task
  - type: textarea
    id: gaiyo
    attributes:
      label: 概要
      description: |
        概要を書く。
        概要を書いてください。
  - type: textarea
    id: design
    attributes:
      label: 設計
      description: |
        設計を書く
        - ああ
        - いいい
  - type: checkboxes
    id: ready-check
    attributes:
      label: Ready の条件
      description: ここは触らなくてよい 
      options:
        - label: 条件1
        - label: 条件2
        - label: 条件3
