name: Release
on:
    push:
      tags:
      - 'v*'
jobs:
    goreleaser:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
            with:
              fetch-depth: 0
          - name: Set up Go
            uses: actions/setup-go@v4
          - name: Run GoReleaser
            run: |
                echo ${GITHUB_REF_NAME}
                echo /repos/${{ github.repository }}/releases
                gh api \
                -H "Accept: application/vnd.github+json" \
                --method POST \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                /repos/${{ github.repository }}/releases \
                -f tag_name='${GITHUB_REF_NAME}' \
                -F draft=true \
                -F prerelease=false \
                -F generate_release_notes=true
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
